### ISSUE TITLE
不支持的配置写法

### ISSUE THREAD

**Issue by yhostc** [ElementUI/element-starter#20]
如下代码写法会在我的环境报错，是我的nodejs需要升级到某个版本才可以吗？

我的Node 版本v5.1.1, Npm版本3.3.12
```js
// webpack.config.js
const {
  resolve
} = require('path')
```
错误内容：
```js
(function (exports, require, module, __filename, __dirname) { const {
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at requireConfig (/Users/yhostc/Wechat/element-starter/node_modules/.2.2.0-rc.4@webpack/bin/convert-argv.js:96:18)
    at /Users/yhostc/Wechat/element-starter/node_modules/.2.2.0-rc.4@webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
```

**Comment by QingWei-Li** [comment]
Node >= 6

**Comment by yhostc** [comment]
Ok, 已解决，thx
