### ISSUE TITLE
Build Failed when npm run build

### ISSUE THREAD

**Issue by andy-zhangtao** [ElementUI/element-starter#47]
When execute "npm run build", the webpack throw a error.
``` js
ERROR in index.js?74362200ea0bc218cad7 from UglifyJs
Unexpected token: punc (() [index.js?74362200ea0bc218cad7:512,6]

ERROR in vendor.js?f0e7a8ae26abe932fe28 from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/source-map/lib/source-map-consumer.js:20:19)
    at filterdFiles.forEach (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:61:20)
    at Array.forEach (native)
    at Compilation.compilation.plugin (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:40:18)
    at next (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/tapable/lib/Tapable.js:140:14)
    at Compilation.compilation.plugin (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:230:5)
    at Compilation.applyPluginsAsyncSeries (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/tapable/lib/Tapable.js:142:13)
    at self.applyPluginsAsync.err (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/webpack/lib/Compilation.js:635:10)
    at next (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.compilation.plugin.callback (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/webpack/lib/ProgressPlugin.js:113:6)
    at Compilation.applyPluginsAsyncSeries (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/tapable/lib/Tapable.js:142:13)
    at sealPart2 (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/webpack/lib/Compilation.js:631:9)
    at next (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.compilation.plugin (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/webpack/lib/ProgressPlugin.js:109:6)
    at Compilation.applyPluginsAsyncSeries (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/tapable/lib/Tapable.js:142:13)
    at Compilation.seal (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/webpack/lib/Compilation.js:579:8)
    at /Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/webpack/lib/Compiler.js:493:16
    at /Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/zhangtao/SourceCode/FrontProject/SakersVue/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

If run dev, there will be OK. Below is my webpack.config.js for your reference. 
``` js
const resolve = require('path').resolve
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const url = require('url')
const publicPath = ''
const env = process.env.NODE_ENV || 'development';
const shadow_url = process.env.SHADOW_URL;

module.exports = (options = {}) => ({
    entry: {
        vendor: './src/vendor',
        index: './src/main.js'
    },
    output: {
        path: resolve(__dirname, 'dist'),
        filename: options.dev ? '[name].js' : '[name].js?[chunkhash]',
        chunkFilename: '[id].js?[chunkhash]',
        publicPath: options.dev ? '/assets/' : publicPath
    },
    module: {
        rules: [{
                test: /\.vue$/,
                use: ['vue-loader']
            },
            {
                test: /\.js$/,
                use: ['babel-loader'],
                exclude: /node_modules/
            },
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader', 'postcss-loader']
            },
            {
                test: /\.(png|jpg|jpeg|gif|eot|ttf|woff|woff2|svg|svgz)(\?.+)?$/,
                use: [{
                    loader: 'url-loader',
                    options: {
                        limit: 10000
                    }
                }]
            }
        ]
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            names: ['vendor', 'manifest']
        }),
        new HtmlWebpackPlugin({
            template: 'src/index.html'
        }),
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify(env),
                SHADOW_URL: JSON.stringify(shadow_url),
                SHADOW_API_PROXY: '/proxy/'
            }
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false
            }
        })
    ],
    resolve: {
        alias: {
            '~': resolve(__dirname, 'src'),
            'vue': 'vue/dist/vue.js'
        }
    },
    devServer: {
        host: '127.0.0.1',
        port: 8010,
        proxy: {
            '/api/': {
                target: 'http://127.0.0.1:8080',
                changeOrigin: true,
                pathRewrite: {
                    '^/api': ''
                }
            }
        },
        historyApiFallback: {
            index: url.parse(options.dev ? '/assets/' : publicPath).pathname
        }
    },
    devtool: options.dev ? '#eval-source-map' : '#source-map'
})
```

**Comment by andy-zhangtao** [comment]
My misstake. I invoke UglifyJs twice, so throw this error. But I use original webpack.config.js, it throw another error. 
```
ERROR in index.js?b6ed2c21547a30ed4e1a from UglifyJs
Unexpected token: punc (() [index.js?b6ed2c21547a30ed4e1a:512,6]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! element-starter@ build: `rimraf dist && webpack -p --progress --hide-modules`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the element-starter@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I use below configure,
```
const resolve = require('path').resolve
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const url = require('url')
const publicPath = ''



module.exports = (options = {}) => ({
    entry: {
        vendor: './src/vendor',
        index: './src/main.js'
    },
    output: {
        path: resolve(__dirname, 'dist'),
        filename: options.dev ? '[name].js' : '[name].js?[chunkhash]',
        chunkFilename: '[id].js?[chunkhash]',
        publicPath: options.dev ? '/assets/' : publicPath
    },
    module: {
        rules: [{
                test: /\.vue$/,
                use: ['vue-loader']
            },
            {
                test: /\.js$/,
                use: ['babel-loader'],
                exclude: /node_modules/
            },
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader', 'postcss-loader']
            },
            {
                test: /\.(png|jpg|jpeg|gif|eot|ttf|woff|woff2|svg|svgz)(\?.+)?$/,
                use: [{
                    loader: 'url-loader',
                    options: {
                        limit: 10000
                    }
                }]
            }
        ]
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            names: ['vendor', 'manifest']
        }),
        new HtmlWebpackPlugin({
            template: 'src/index.html'
        })
    ],
    resolve: {
        alias: {
            '~': resolve(__dirname, 'src')
        }
    },
    devServer: {
        host: '127.0.0.1',
        port: 8010,
        proxy: {
            '/api/': {
                target: 'http://127.0.0.1:8080',
                changeOrigin: true,
                pathRewrite: {
                    '^/api': ''
                }
            }
        },
        historyApiFallback: {
            index: url.parse(options.dev ? '/assets/' : publicPath).pathname
        }
    },
    devtool: options.dev ? '#eval-source-map' : '#source-map'
})
```

I am newer to VUE, so please tell me how to fix it. Thanks.

**Comment by andy-zhangtao** [comment]
It fixed!

I add .babelrc, and use 'vue-app' for presets.
```
{
    "presets": [
        "vue-app"
    ],
    "plugins": []
} 
```

I don't know why it works in original project, but doesn't work in my project. But it works now, so I close this issue. 

Thanks
