### ISSUE TITLE
npm run dev时报错

### ISSUE THREAD

**Issue by mzy1205** [ElementUI/element-starter#50]
我的系统是deepin15.3，自己有一个搬瓦工的centos6.5的服务器，在(sudo) npm run dev 时都报错，又下了淘宝的cnpm也是报这个错，端口改过之后无效，node也没启动过。同事的mac和win7都没问题。是还需要什么配置吗？网上也没搜到别人碰到过这种问题
> element-starter@ dev /var/www/element-starter-master
> webpack-dev-server --inline --hot --env.dev

Project is running at http://127.0.0.1:10101/
webpack output is served from /assets/
404s will fallback to /assets/
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:10101
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at Server.setupListenHandle [as _listen2] (net.js:1322:14)
    at listenInCluster (net.js:1370:12)
    at doListen (net.js:1492:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! element-starter@ dev: `webpack-dev-server --inline --hot --env.dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the element-starter@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/itzj00100/.npm/_logs/2017-09-18T13_00_19_265Z-debug.log

**Comment by mzy1205** [comment]
昨晚回家又在我自己的Ubuntu16上试了一下，是可以的，今天早上过来重新下了一份zip包，也是可以的。很奇怪。。所以目前来看，方法是重启。。
