### ISSUE TITLE
webpack.config.js疑问

### ISSUE THREAD

**Issue by Plortinus** [ElementUI/element-starter#9]
根据这个[Issue](https://github.com/vuejs-templates/webpack/issues/215)，是不是需要添加`vue`的`alias`？

实际项目中，也用到别的插件，不加alias的话终端里会报`[Vue warn]: You are using the runtime-only build of Vue where the template option is not available. Either pre-compile the templates into render functions, or use the compiler-included build.`

**Comment by QingWei-Li** [comment]
如果你打算使用 runtime + compiler 版本的 Vue 的话就配置，不过大多数情况下都是选择预编译好模板（用 vue-loader 和 *.vue 文件）

**Comment by Plortinus** [comment]
比如说，我在项目中用[vue-region-picker](https://github.com/QingWei-Li/vue-region-picker)的时候，就得加`vue`的`alias`

**Comment by QingWei-Li** [comment]
.......😂 那个是当初没理解 Vue 2 的这个特性，然后一直没修复 我这两天弄好

**Comment by yuanyuanshen** [comment]
这个问题是怎么导致的呢？

Uncaught TypeError: _vm._h is not a function
    at Proxy.render (eval at <anonymous> (http://localhost:1314/dist/build.js:1301:1), <anonymous>:6130:46)
    at VueComponent.Vue._render (eval at <anonymous> (http://localhost:1314/dist/build.js:820:1), <anonymous>:2952:22)
    at VueComponent.eval (eval at <anonymous> (http://localhost:1314/dist/build.js:820:1), <anonymous>:2189:21)
    at Watcher.get (eval at <anonymous> (http://localhost:1314/dist/build.js:820:1), <anonymous>:1652:27)
    at new Watcher (eval at <anonymous> (http://localhost:1314/dist/build.js:820:1), <anonymous>:1644:12)
    at VueComponent.Vue._mount (eval at <anonymous> (http://localhost:1314/dist/build.js:820:1), <anonymous>:2188:19)
    at VueComponent.Vue$2.$mount (eval at <anonymous> (http://localhost:1314/dist/build.js:820:1), <anonymous>:5978:15)
    at init (eval at <anonymous> (http://localhost:1314/dist/build.js:820:1), <anonymous>:2500:11)
    at createComponent (eval at <anonymous> (http://localhost:1314/dist/build.js:820:1), <anonymous>:4052:9)
    at createElm (eval at <anonymous> (http://localhost:1314/dist/build.js:820:1), <anonymous>:3995:9)
